# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clientanalytics_dmc.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'clientanalytics_dmc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63lientanalytics_dmc.proto\"O\n\x08LogEvent\x12\x15\n\revent_time_ms\x18\x01 \x01(\x03\x12\x12\n\nevent_code\x18\x0b \x01(\x05\x12\x18\n\x10source_extension\x18\x06 \x01(\x0c\"u\n\nClientInfo\x12\x30\n\x0b\x63lient_type\x18\x01 \x01(\x0e\x32\x16.ClientInfo.ClientTypeH\x00\x88\x01\x01\"%\n\nClientType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06PYTHON\x10\x06\x42\x0e\n\x0c_client_type\"5\n\x11\x42\x61tchedLogRequest\x12 \n\x0blog_request\x18\x01 \x03(\x0b\x32\x0b.LogRequest\"\xaa\x01\n\nLogRequest\x12\x17\n\x0frequest_time_ms\x18\x04 \x01(\x03\x12 \n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x0b.ClientInfo\x12\x12\n\nlog_source\x18\x02 \x01(\x05\x12\x1c\n\tlog_event\x18\x03 \x03(\x0b\x32\t.LogEvent\x12/\n\x08qos_tier\x18\t \x01(\x0e\x32\x1d.QosTierConfiguration.QosTier\"\xc3\x01\n\x14QosTierConfiguration\x12/\n\x08qos_tier\x18\x02 \x01(\x0e\x32\x1d.QosTierConfiguration.QosTier\x12\x12\n\nlog_source\x18\x03 \x01(\x05\"f\n\x07QosTier\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x12\n\x0eUNMETERED_ONLY\x10\x01\x12\x16\n\x12UNMETERED_OR_DAILY\x10\x02\x12\x17\n\x13\x46\x41ST_IF_RADIO_AWAKE\x10\x03\x12\t\n\x05NEVER\x10\x04\"g\n\x10QosTiersOverride\x12\x35\n\x16qos_tier_configuration\x18\x01 \x03(\x0b\x32\x15.QosTierConfiguration\x12\x1c\n\x14qos_tier_fingerprint\x18\x02 \x01(\x03\"v\n\x0bLogResponse\x12%\n\x18next_request_wait_millis\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12#\n\x08qos_tier\x18\x03 \x01(\x0b\x32\x11.QosTiersOverrideB\x1b\n\x19_next_request_wait_millisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clientanalytics_dmc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGEVENT']._serialized_start=29
  _globals['_LOGEVENT']._serialized_end=108
  _globals['_CLIENTINFO']._serialized_start=110
  _globals['_CLIENTINFO']._serialized_end=227
  _globals['_CLIENTINFO_CLIENTTYPE']._serialized_start=174
  _globals['_CLIENTINFO_CLIENTTYPE']._serialized_end=211
  _globals['_BATCHEDLOGREQUEST']._serialized_start=229
  _globals['_BATCHEDLOGREQUEST']._serialized_end=282
  _globals['_LOGREQUEST']._serialized_start=285
  _globals['_LOGREQUEST']._serialized_end=455
  _globals['_QOSTIERCONFIGURATION']._serialized_start=458
  _globals['_QOSTIERCONFIGURATION']._serialized_end=653
  _globals['_QOSTIERCONFIGURATION_QOSTIER']._serialized_start=551
  _globals['_QOSTIERCONFIGURATION_QOSTIER']._serialized_end=653
  _globals['_QOSTIERSOVERRIDE']._serialized_start=655
  _globals['_QOSTIERSOVERRIDE']._serialized_end=758
  _globals['_LOGRESPONSE']._serialized_start=760
  _globals['_LOGRESPONSE']._serialized_end=878
# @@protoc_insertion_point(module_scope)
