# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: convert_usage_extension.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import convert_usage_pb2 as convert__usage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63onvert_usage_extension.proto\x1a\x13\x63onvert_usage.proto\"M\n\x15\x43onvertUsageExtension\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12$\n\rconvert_usage\x18\x02 \x01(\x0b\x32\r.ConvertUsageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convert_usage_extension_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONVERTUSAGEEXTENSION._serialized_start=54
  _CONVERTUSAGEEXTENSION._serialized_end=131
# @@protoc_insertion_point(module_scope)
